export const SIGNUP = 'SIGNUP'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION'
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION'

export const GET_PROJECTS = 'GET_PROJECTS'
export const GET_PROJECT = 'GET_PROJECT'
export const LIKE_PROJECT = 'LIKE_PROJECT'
export const DISLIKE_PROJECT = 'DISLIKE_PROJECT'

export const GET_CATEGORIES = 'GET_CATEGORIES'
