
export const LOGIN = {
  REQUEST: 'LOGIN_REQUEST',
  SUCCESS: 'LOGIN_SUCCESS',
  ERROR: 'LOGIN_ERROR'
}

export const SIGNUP = {
  REQUEST: 'SIGNUP_REQUEST',
  SUCCESS: 'SIGNUP_REQUEST',
  ERROR: 'SIGNUP_ERROR'
}
