
export const LOGIN = {
  REQUEST: 'LOGIN_REQUEST',
  SUCCESS: 'LOGIN_SUCCESS',
  ERROR: 'LOGIN_ERROR'
}

export const SIGNUP = {
  REQUEST: 'SIGNUP_REQUEST',
  SUCCESS: 'SIGNUP_SUCCESS',
  ERROR: 'SIGNUP_ERROR'
}

export const LOGOUT = {
  REQUEST: 'LOGOUT_REQUEST',
  SUCCESS: 'LOGOUT_SUCCESS'
}

export const AUTH_TOKEN = {
  SET: 'SET_AUTH_TOKEN',
  REMOVE: 'REMOVE_AUTH_TOKEN'
}

export const USER = {
  FETCH_REQUEST: 'FETCH_USER_REQUEST',
  FETCH_ERROR: 'FETCH_USER_ERROR',
  FETCH_SUCCESS: 'FETCH_USER_SUCCESS'
}

export const PROJECT = {
  SAVE: 'PROJECT_SAVE',
  SAVE_SUCCESS: 'PROJECT_SAVE_SUCCESS',
  SAVE_ERROR: 'PROJECT_SAVE_ERROR'
}
